# задайте указанные ниже параметры через environment variables

server:
  port: ${SCHEDULER_EXTERNAL_PORT}
spring:
  application:
    name: scheduler
  datasource:
    url: jdbc:postgresql://${SCHEDULER_DATABASE_URL}/${SCHEDULER_DATABASE_NAME}
    username: ${SCHEDULER_DATABASE_USERNAME}
    password: ${SCHEDULER_DATABASE_PASSWORD}
    driver: org.postgresql.Driver
    initialization-mode: always
  flyway:
    enabled: true
    locations: classpath:db/migration
  docker:
    compose:
      enabled: true
